### ISSUE TITLE
not swithcing in

### ISSUE THREAD

**Issue by markantonay** [Rolice/laravel-db-switch#1]
Hi,
![image](https://user-images.githubusercontent.com/2108131/37627689-8d9cc080-2c10-11e8-9e6d-001c4648a6df.png)
I've tried doing the DbSwitch::connectionTo but still it hasnt switch to the other DB ( see image)
little help?

Thanks :)

**Comment by Rolice** [comment]
Hello!
I think you need to instantiate connection with the array first. The method `connectionTo` sets the current connection, but you are passing simple configuration array.

Can you try creating new connection manually with this configuration array and pass the object as second parameter, instead of `$dynamicdb` array variable?

**Comment by markantonay** [comment]
I manage to connect but edditing this
` Config::set("database.connections.{$key}.database", $database);`
to this
`Config::set("database.connections.{$key}",` $database);`
